// lib/knowledge.ts

export interface ExerciseKnowledge {
  name: string;
  category: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  equipment: string[];
  instructions: string[];
  common_mistakes: string[];
  regressions: string[]; // Easier alternatives
  progressions: string[]; // Harder alternatives
}

export interface MealKnowledge {
  name: string;
  category: string;
  prep_instructions: string[];
  substitutions: string[];
  budget_friendly: boolean;
}

// A scalable, static application-level database
export const EXERCISE_KB: Record<string, ExerciseKnowledge> = {
  "Push-ups": {
    name: "Push-ups",
    category: "Upper Body Push",
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    instructions: [
      "Start in a high plank position with hands slightly wider than shoulder-width.",
      "Keep your core engaged and body in a straight line from head to heels.",
      "Lower your body until your chest nearly touches the floor.",
      "Push back up to the starting position."
    ],
    common_mistakes: ["Flaring elbows out too wide", "Letting the lower back sag", "Not going through a full range of motion"],
    regressions: ["Knee Push-ups", "Incline Push-ups (hands on a bench/wall)"],
    progressions: ["Decline Push-ups", "Diamond Push-ups", "Weighted Push-ups"]
  },
  "Squats": {
    name: "Squats",
    category: "Lower Body",
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    instructions: [
      "Stand with feet shoulder-width apart, toes slightly pointed out.",
      "Push your hips back and bend your knees as if sitting in a chair.",
      "Keep your chest up and ensure your knees track over your toes.",
      "Push through your whole foot to stand back up."
    ],
    common_mistakes: ["Letting knees cave inward", "Lifting heels off the floor", "Rounding the lower back"],
    regressions: ["Box Squats (sitting onto a chair)", "Assisted Squats (holding a doorway)"],
    progressions: ["Jump Squats", "Goblet Squats", "Pistol Squats"]
  },
  // Add more as needed...
};

export const MEAL_KB: Record<string, MealKnowledge> = {
  "Oatmeal with Berries": {
    name: "Oatmeal with Berries",
    category: "Breakfast",
    budget_friendly: true,
    prep_instructions: [
      "Boil water or milk in a small pot.",
      "Stir in rolled oats and reduce heat to low.",
      "Simmer for 5 minutes, stirring occasionally.",
      "Top with fresh or frozen berries and a pinch of cinnamon."
    ],
    substitutions: [
      "Swap oats for quinoa flakes if gluten-free.",
      "Swap berries for sliced banana or apple.",
      "Add protein powder for extra protein."
    ]
  }
};

// Helper function for fuzzy matching items generated by AI to our KB
export function findKnowledge(itemName: string, type: 'workout' | 'diet') {
  const kb = type === 'workout' ? EXERCISE_KB : MEAL_KB;
  const key = Object.keys(kb).find(k => itemName.toLowerCase().includes(k.toLowerCase()));
  return key ? kb[key] : null;
}
